#!/usr/bin/env bash
#
# build-offline-bundle.sh — produce a self-contained offline deployment bundle.
#
# Athena deploys by source-build (the compose app services use `build:`, not
# `image:`), so there is no ready-made package to hand an operator. This script
# turns the repo into one: it builds the app images, pulls every third-party
# base image, `docker save`s them all into a single tarball, and packages that
# alongside the compose files + an `image:` override + a one-shot load/up script.
#
# Run this ON A MACHINE WITH A DOCKER DAEMON (it cannot run on a daemon-less box).
# The resulting bundle then deploys on an offline/air-gapped host with no build
# step and no registry access:
#     tar xzf athena-offline-<tag>.tar.gz && cd athena-offline-<tag>
#     cp .env.example prod.env && $EDITOR prod.env
#     ./load-and-up.sh
#
# Key trick: docker-compose.offline.yml pins image: athena/<svc>:<tag> on the
# three build services. The SAME file is used at build time (so the built images
# get that exact tag) and at deploy time with `up --no-build` (so compose uses
# the loaded images instead of rebuilding). This avoids relying on compose's
# project-name image naming, which differs ('_' vs '-') across compose versions.
#
# Usage:
#   scripts/build-offline-bundle.sh [--tag TAG] [--out PATH] [--no-pull]
#                                   [--compose-files "-f a.yml -f b.yml"]
# Options:
#   --tag TAG            Image tag (default: git short SHA, else 'local')
#   --out PATH           Output tarball path (default: dist/athena-offline-<tag>.tar.gz)
#   --no-pull            Skip pulling third-party images (assume already local)
#   --compose-files STR  Override the compose -f set (default: base + prod)
#   -h, --help           Show this help
#
# shellcheck disable=SC2086  # $COMPOSE_FILES / $CF_ALL are intentionally word-split into repeated -f flags
set -euo pipefail

# ---- locate repo root -------------------------------------------------------
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---- defaults ---------------------------------------------------------------
TAG=""
OUT=""
NO_PULL=0
COMPOSE_FILES="-f docker-compose.yml -f docker-compose.prod.yml"
APP_SERVICES=(ecm-core ecm-frontend ml-service)   # the build: services we tag ourselves
ENV_FILE=".env.example"                            # used only to satisfy interpolation at build/config time

# ---- parse args -------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)            TAG="${2:?--tag needs a value}"; shift 2 ;;
    --out)            OUT="${2:?--out needs a value}"; shift 2 ;;
    --no-pull)        NO_PULL=1; shift ;;
    --compose-files)  COMPOSE_FILES="${2:?--compose-files needs a value}"; shift 2 ;;
    -h|--help)        sed -n '2,40p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$TAG" ]]; then
  TAG="$(git rev-parse --short HEAD 2>/dev/null || echo local)"
fi
[[ -z "$OUT" ]] && OUT="dist/athena-offline-${TAG}.tar.gz"

# ---- preflight --------------------------------------------------------------
echo "==> Preflight"
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker not found"; exit 1; }
docker compose version >/dev/null 2>&1 || {
  echo "ERROR: 'docker compose' (v2 plugin) required; legacy docker-compose v1 is unsupported."; exit 1; }
docker info >/dev/null 2>&1 || {
  echo "ERROR: Docker daemon not reachable. This script must run on a host with a running daemon."; exit 1; }
[[ -f docker-compose.yml && -f docker-compose.prod.yml ]] || {
  echo "ERROR: must run from the Athena repo root (compose files not found)."; exit 1; }
[[ -f "$ENV_FILE" ]] || { echo "ERROR: $ENV_FILE not found."; exit 1; }
echo "    tag=$TAG  out=$OUT  compose=[$COMPOSE_FILES]"

SRC_COMMIT="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ---- staging dir ------------------------------------------------------------
STAGE_NAME="athena-offline-${TAG}"
STAGE="dist/${STAGE_NAME}"
rm -rf "$STAGE"
mkdir -p "$STAGE"

# ---- 1. generate the image: override (pins built images to a fixed tag) -----
echo "==> Generating docker-compose.offline.yml (pinning ${APP_SERVICES[*]} to athena/<svc>:${TAG})"
OFFLINE_YML="$STAGE/docker-compose.offline.yml"
{
  echo "# Generated by scripts/build-offline-bundle.sh — DO NOT edit by hand."
  echo "# Pins the build services to pre-loaded images so 'up --no-build' uses them."
  echo "services:"
  for svc in "${APP_SERVICES[@]}"; do
    echo "  ${svc}:"
    echo "    image: athena/${svc}:${TAG}"
  done
} > "$OFFLINE_YML"

# Compose -f set including the override (used for build / config / images).
CF_ALL="$COMPOSE_FILES -f $OFFLINE_YML"

# ---- 2. build the app images (compose carries any build args/targets) -------
echo "==> Building app images"
# shellcheck disable=SC2086
docker compose --env-file "$ENV_FILE" $CF_ALL build "${APP_SERVICES[@]}"

# ---- 3. resolve the full image list (apps pinned + all third-party) ---------
echo "==> Resolving image list"
# (while-read instead of mapfile so this also runs under macOS bash 3.2)
IMAGES=()
while IFS= read -r _img_line; do
  [[ -n "$_img_line" ]] && IMAGES+=("$_img_line")
done < <(docker compose --env-file "$ENV_FILE" $CF_ALL config --images | sort -u)
[[ ${#IMAGES[@]} -gt 0 ]] || { echo "ERROR: resolved 0 images"; exit 1; }
printf '    %s\n' "${IMAGES[@]}"

# ---- 4. pull third-party images (skip the ones we built ourselves) ----------
if [[ "$NO_PULL" -eq 0 ]]; then
  echo "==> Pulling third-party base images"
  for img in "${IMAGES[@]}"; do
    case "$img" in
      athena/*) echo "    (skip built: $img)" ;;
      *) echo "    pull $img"; docker pull "$img" ;;
    esac
  done
else
  echo "==> --no-pull: assuming all third-party images are already local"
fi

# ---- 5. save every image into one layer-deduplicated, gzipped tar -----------
echo "==> Saving images (this can be several GB and take a while)"
docker save "${IMAGES[@]}" | gzip > "$STAGE/images.tar.gz"

# ---- 6. assemble the bundle -------------------------------------------------
echo "==> Assembling bundle"
cp docker-compose.yml docker-compose.prod.yml "$STAGE/"
cp "$ENV_FILE" "$STAGE/.env.example"

# 6a. one-shot load + up script for the offline host
cat > "$STAGE/load-and-up.sh" <<'LOADEOF'
#!/usr/bin/env bash
# Load the bundled images and start the stack — run on the offline target host.
set -euo pipefail
cd "$(dirname "$0")"

docker compose version >/dev/null 2>&1 || {
  echo "ERROR: 'docker compose' (v2 plugin) required."; exit 1; }
if [[ ! -f prod.env ]]; then
  echo "ERROR: prod.env not found. Run: cp .env.example prod.env  (then edit it)."; exit 1; fi

echo "==> Loading images (docker load)"
gunzip -c images.tar.gz | docker load

CF="-f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.offline.yml"
echo "==> Starting stack (up -d --no-build)"
# shellcheck disable=SC2086
docker compose $CF --env-file prod.env up -d --no-build
echo "==> Status"
# shellcheck disable=SC2086
docker compose $CF --env-file prod.env ps
LOADEOF
chmod +x "$STAGE/load-and-up.sh"

# 6b. manifest
cat > "$STAGE/MANIFEST.txt" <<EOF
Athena offline deployment bundle
================================
tag:          ${TAG}
source commit:${SRC_COMMIT}
built (UTC):  ${BUILD_DATE}
compose:      ${COMPOSE_FILES} + docker-compose.offline.yml

Images (docker save'd into images.tar.gz):
$(printf '  - %s\n' "${IMAGES[@]}")
EOF

# 6c. offline README
cat > "$STAGE/README.offline.md" <<EOF
# Athena Offline Deployment Bundle (\`${TAG}\`)

Self-contained: no source build and no registry access needed on the target host.

## Requirements (target host)
- Docker 20.10+ with the Compose **v2** plugin (\`docker compose\`)
- Hardware per \`docs/INSTALLATION.md\` (prod: 8 cores / 32 GB / SSD)

## Steps
1. \`tar xzf ${STAGE_NAME}.tar.gz && cd ${STAGE_NAME}\`
2. \`cp .env.example prod.env\` then edit \`prod.env\` (set real secrets, hostnames, TLS).
3. \`./load-and-up.sh\`

\`load-and-up.sh\` runs \`docker load\` then
\`docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.offline.yml --env-file prod.env up -d --no-build\`.

## Notes
- \`docker-compose.offline.yml\` pins the app images to the exact tags loaded from \`images.tar.gz\`; \`--no-build\` guarantees no rebuild.
- To trim size, remove services you don't need from \`docker-compose.offline.yml\` and re-tar — or rebuild the bundle with a narrower compose set.
- See \`docs/INSTALLATION.md\` for full config, ports, and troubleshooting.
- Run the production preflight before going live: \`scripts/prod-deploy-preflight.sh --env-file prod.env --require-daemon\`.
EOF

# ---- 7. tar it up -----------------------------------------------------------
echo "==> Creating $OUT"
mkdir -p "$(dirname "$OUT")"
tar -C dist -czf "$OUT" "$STAGE_NAME"

SIZE="$(du -h "$OUT" | cut -f1)"
echo
echo "==> Done."
echo "    bundle: $OUT  (${SIZE})"
echo "    images: ${#IMAGES[@]}"
echo "    deploy: tar xzf $(basename "$OUT") && cd $STAGE_NAME && cp .env.example prod.env && ./load-and-up.sh"
